# Generated by Django 3.0.7 on 2020-06-07 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200607_0645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='title',
            new_name='item',
        ),
    ]
